### ISSUE TITLE
Refactor Scaler Class

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/PowerSimData#188]
- [x] Create two classes, `TransformGrid` and `ScaleProfile` that apply transformations listed in the change table to a `Grid` object and a profile. 
- [x] Write tests for these new objects.
- [x] Uses these objects in the scenario framework
- [x] Implement a method that allows to retrieved the transformed grid in the building phase of the scenario.
- [x] Fix a bug in the `Analyze` class by using the `Grid` object coming from the instantiation of the Grid class via the *input.mat* of the scenario instead of the TAMU files.
