### ISSUE TITLE
Grid model selection

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/PowerSimData#344]
We want to be able to select the grid model that will be used for a scenario. To implement this feature, we need to perform the following tasks:
- [x] Reorganize the `hydro`, `solar` and `wind` profiles since the profiles are grid dependent
- [x] Refactor the `Create`, `_Builder` and `CSV` classes in the `powersimdata.scenario.create` module to i) handle the newly organized profile and ii) let the user select the grid model of her/his choice.
- [x] Add a new column in the ***ScenarioList.csv*** file that specifies the grid model used for the scenario.

**Comment by danielolsen** [comment]
One thing we discussed today that I don't see in any of the issues:
- Currently, there are four profiles that are required to run a scenario: demand, hydro, solar, wind.
- In the future, we will almost definitely want to specify additional profiles, e.g. flexible demand.
- We will only want to specify these profiles when running a version of REISE.jl that can interpret them.
- Therefore, we may need to specify both the Grid model and the version of the Simulation Engine to be run in order to display a meaningful profiles selection to the user (since if they run with an old version of the REISE.jl, they should not be given the option to specify profiles which will not be used).
