### ISSUE TITLE
Consolidate Data Access Code

### ISSUE THREAD

**Issue by ahurli** [Breakthrough-Energy/PowerSimData#538]
### Description
The proposed change is to refactor the code such that read/write operations are handled in a consolidated place (i.e. either input_data or data_access).

### Initiative / Goal (Business)
This will help us move fully to `pyfilesystem` as currently `pyfilesystem` is only used to move or delete existing files. By consolidating the read/write parts of data access, we should be able to then update these functions to use `pyfilesystem` more easily and thus be able to realize the full benefits of having a fully-abstracted file system (e.g. easier to switch between different filesystems, support for multiple data sources and/or scenario lists, etc).

### Success (Optional)
Using `pyfilesystem` for all file system operations.

### Acceptance criteria
Remove direct read/writes of data to local file system (i.e. pandas, pickle, or scipy.io) and consolidate path building from anywhere outside of data access/input data.

- [x] Define expected read/write functionality outside of powersimdata workflow (e.g. export_case_mat in powersimdata/input/export_data was refactored out so that ext. collaborators could manually save a case.mat to examine/test without starting a simulation). How and where do we need to expose these functions, both for now and in the future?
- [x] Decide design for where the new file objects will be created and what their lifecycle looks like
- [x] Update direct-to-local-filesystem read/writes of data (i.e. pandas, pickle, or scipy.io)
    - [ ] input/change_table.py: pickle dump
    - [ ] input/export_data.py: savemat, pandas csv
    - [ ] data_access/csv_store.py: pandas csv
    - [ ] output/output_data.py: pandas pickle
- [ ] Consolidate path building from anywhere outside of data access/input_data (in addition to above)
    - [ ] create.py
    - [ ] execute.py
    - [ ] analyze.py
    - [ ] (bonus) move.py
    - [ ] (bonus) delete.py

[Dropbox Paper with more in-depth notes about this epic](https://www.dropbox.com/scl/fi/uwynx5md5ut6ks0od9dsu/Data-Consolidation.paper?dl=0&rlkey=cc5ct4harvc0b2qw8jiloyfw7)

### Owner
@ahurli 

### Support
@rouille @jon-hagg @BainanXia @danielolsen
