### ISSUE TITLE
European Grid model

### ISSUE THREAD

**Issue by rouille** [Breakthrough-Energy/PowerSimData#630]
Create a PyPSA `Network` object of the PyPSA-Eur grid model available on [Zenodo](https://doi.org/10.5281/zenodo.3601882) for various spatial resolution.
- [x] Create a `TUB` class responsible for fetching the data and instantiate the `Network` class
- [x] Create mapping (country --> loadzone, country --> timezone, etc.) for Europe
- [x] Refactor further the `ModelImmutables` class to include Europe or any non-US model. This include the `area_to_loadzone` function.

**Comment by danielolsen** [comment]
For Scenarios which come from one of the pre-prepared European models on Zenodo, can we enable the `get_demand`, `get_solar` etc. methods via inspection of the cached NetCDF file? It could be a stand-in for the profile CSVs as the 'base' profile information which gets transformed.

**Comment by rouille** [comment]
> For Scenarios which come from one of the pre-prepared European models on Zenodo, can we enable the `get_demand`, `get_solar` etc. methods via inspection of the cached NetCDF file? It could be a stand-in for the profile CSVs as the 'base' profile information which gets transformed.

It is an option. I did not think about it too much yet.
